import Head from "next/head";
import { Inter } from "next/font/google";
import { deleteCookie } from "cookies-next";

export default function Home() {

  const logout = () => {
    deleteCookie("userDetails");
    window.location.reload();
  };

  return (
    <>
      <Head>
        <title>LoginApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>You Are Authenticated</h1>
      <form onSubmit={logout}>
        <button>logout</button>
      </form>
    </>
  );
}
